/* 卡牌参数配置 */
var cardConfig = {
  /*卡牌种类*/
  cardType : [
    {
      key:'0',
      name:'怪兽卡',
      list:[
        {key:'0',name:'通常'},
        {key:'1',name:'效果'},
        {key:'2',name:'仪式'},
        {key:'3',name:'融合'},
        {key:'4',name:'同调'},
        {key:'5',name:'超量'}
      ]
    },{
      key:'1',
      name:'魔法卡',
      list:[
        {key:'0',name:'通常'},
        {key:'1',name:'永续'},
        {key:'2',name:'仪式'},
        {key:'3',name:'速攻'},
        {key:'4',name:'装备'},
        {key:'5',name:'场地'}
      ]
    },{
      key:'2',
      name:'陷阱卡',
      list:[
        {key:'0',name:'通常'},
        {key:'1',name:'永续'},
        {key:'2',name:'反击'}
      ]
    }
  ],
  /*怪兽属性*/
  cardNature:[
    {key:'0',name:'神'},
    {key:'1',name:'光'},
    {key:'2',name:'地'},
    {key:'3',name:'暗'},
    {key:'4',name:'风'},
    {key:'5',name:'水'},
    {key:'6',name:'炎'}
  ],
  /*种族*/
  cardRace:[
    {key:'0',name:'恶魔族'},
    {key:'1',name:'天使族'},
    {key:'2',name:'机械族'},
    {key:'3',name:'兽战士族'},
    {key:'4',name:'战士族'},
    {key:'5',name:'魔法师族'},
    {key:'6',name:'植物族'},
    {key:'7',name:'岩石族'},
    {key:'8',name:'兽族'},
    {key:'9',name:'水族'},
    {key:'10',name:'鱼族'},
    {key:'11',name:'海龙族'},
    {key:'12',name:'雷族'},
    {key:'13',name:'风族'},
    {key:'14',name:'炎族'},
    {key:'15',name:'恐龙族'},
    {key:'16',name:'不死族'},
    {key:'17',name:'昆虫族'},
    {key:'18',name:'龙族'},
    {key:'19',name:'鸟兽族'},
    {key:'20',name:'幻神族'},
    {key:'21',name:'精灵族'}
  ]
};